Lyzev/Schizoid

- src/main/java/dev/lyzev/api/jna/DwmApi.java
- src/main/kotlin/dev/lyzev/api/events/Events.kt
- src/main/kotlin/dev/lyzev/api/imgui/theme/ImGuiThemes.kt
- src/main/kotlin/dev/lyzev/api/theme/OSTheme.kt
- src/main/kotlin/dev/lyzev/schizoid/Schizoid.kt
- src/main/kotlin/dev/lyzev/schizoid/feature/features/gui/guis/ImGuiScreenFeature.kt
- src/main/kotlin/dev/lyzev/schizoid/feature/features/module/modules/render/FeatureDarkTitleBar.kt
> Add dark mode

- README.md
- build.gradle.kts
this allows for profiling to improve performance
> fix Minecraft Client run configuration

- src/main/kotlin/dev/lyzev/api/setting/settings/SettingClientColor.kt
> adding color setting

- src/main/kotlin/dev/lyzev/api/opengl/shader/Shaders.kt
- src/main/kotlin/dev/lyzev/api/setting/settings/SettingClientColor.kt
- src/main/kotlin/dev/lyzev/schizoid/feature/features/module/modules/render/ModuleToggleableColorGrading.kt
- src/main/resources/assets/schizoid/shaders/core/ColorGrading/ColorGrading_FP.glsl
- src/main/resources/assets/schizoid/shaders/core/ColorGrading/ColorGrading_VP.glsl
- src/main/resources/assets/schizoid/shaders/include/FilmicTonemap.glsl
- src/main/resources/assets/schizoid/shaders/include/Temperature.glsl
> added color grading feature

- build.gradle.kts
- gradle/libs.versions.toml
- src/main/kotlin/dev/lyzev/api/events/Events.kt
- src/main/kotlin/dev/lyzev/api/theme/OSTheme.kt
- src/main/kotlin/dev/lyzev/schizoid/Schizoid.kt
- src/main/kotlin/dev/lyzev/schizoid/feature/features/module/modules/render/ModuleToggleableSpotify.kt
> integrated spotify

- src/main/kotlin/dev/lyzev/schizoid/feature/features/module/modules/render/ModuleToggleableVirtualMousepad.kt
> Add rounded corners for virtual mouse pad

- build.gradle.kts
- gradle/libs.versions.toml
- src/main/kotlin/dev/lyzev/api/events/Events.kt
- src/main/kotlin/dev/lyzev/api/imgui/render/renderable/ImGuiRenderableConfigManager.kt
- src/main/kotlin/dev/lyzev/api/setting/SettingClient.kt
- src/main/kotlin/dev/lyzev/api/setting/SettingInitializer.kt
- src/main/kotlin/dev/lyzev/api/setting/settings/SettingClientColor.kt
- src/main/kotlin/dev/lyzev/api/setting/settings/SettingClientKeybinds.kt
- src/main/kotlin/dev/lyzev/api/setting/settings/SettingClientMultiOption.kt
- src/main/kotlin/dev/lyzev/api/setting/settings/SettingClientMultiText.kt
- src/main/kotlin/dev/lyzev/api/setting/settings/SettingClientOption.kt
- src/main/kotlin/dev/lyzev/api/setting/settings/SettingClientSlider.kt
- src/main/kotlin/dev/lyzev/api/setting/settings/SettingClientSwitch.kt
- src/main/kotlin/dev/lyzev/api/setting/settings/SettingClientText.kt
- src/main/kotlin/dev/lyzev/schizoid/Schizoid.kt
- src/main/kotlin/dev/lyzev/schizoid/feature/features/gui/guis/ImGuiScreenFeature.kt
- src/main/kotlin/dev/lyzev/schizoid/feature/features/module/modules/render/FeatureDarkTitleBar.kt
> 35 suggestion add config system

- src/main/kotlin/dev/lyzev/schizoid/feature/features/module/modules/render/ModuleToggleableMediaPlayer.kt
replaced chrome default artwork with shizoid default artwork
closes #58
> fixed stale artwork

- src/main/java/dev/lyzev/schizoid/injection/mixins/minecraft/client/MixinMouse.java
- src/main/kotlin/dev/lyzev/api/events/Events.kt
- src/main/kotlin/dev/lyzev/schizoid/feature/features/module/modules/render/ModuleToggleableZoom.kt
> add zoom scrolling

- src/main/java/dev/lyzev/schizoid/injection/mixins/minecraft/client/util/MixinWindow.java
- src/main/kotlin/dev/lyzev/api/opengl/shader/Shader.kt
- src/main/kotlin/dev/lyzev/api/opengl/shader/Shaders.kt
- src/main/kotlin/dev/lyzev/api/opengl/shader/blur/BlurHelper.kt
- src/main/kotlin/dev/lyzev/api/opengl/shader/blur/Blurs.kt
- src/main/kotlin/dev/lyzev/api/opengl/shader/blur/blurs/BlurMovingAveragesBox.kt
- src/main/resources/assets/schizoid/shaders/core/Box/Box_FP.glsl
- src/main/resources/assets/schizoid/shaders/core/MovingAveragesBox/MovingAveragesBox_CP.glsl
Known Issue: AMD GPUs seem to don't handle the compute shader correct
close #68
> 68 suggestion moving averages box

- src/main/kotlin/dev/lyzev/schizoid/feature/features/module/modules/render/ModuleToggleableColorGrading.kt
- src/main/resources/assets/schizoid/shaders/core/ColorGrading/ColorGrading_FP.glsl
- src/main/resources/assets/schizoid/shaders/include/Color.glsl
- src/main/resources/assets/schizoid/shaders/include/Temperature.glsl
> added hue shifting in color grading

- src/main/kotlin/dev/lyzev/schizoid/feature/features/module/modules/render/ModuleToggleableMediaPlayer.kt
> fixed the bug

- src/main/kotlin/dev/lyzev/schizoid/feature/features/module/modules/render/ModuleToggleableRearView.kt
> made the image rounded

- src/main/kotlin/dev/lyzev/schizoid/feature/features/module/modules/render/ModuleToggleableMediaPlayer.kt
> removed useless setting

- src/main/kotlin/dev/lyzev/schizoid/feature/features/module/Module.kt
> added flag

- src/main/kotlin/dev/lyzev/schizoid/feature/features/module/modules/render/ModuleToggleableCloseScreen.kt
> added close screen feature

- src/main/resources/assets/schizoid/shaders/core/ColorGrading/ColorGrading_FP.glsl
> fixed calc

- src/main/kotlin/dev/lyzev/api/opengl/WrappedFramebuffer.kt
- src/main/kotlin/dev/lyzev/api/opengl/shader/Shader.kt
- src/main/kotlin/dev/lyzev/api/opengl/shader/Shaders.kt
- src/main/kotlin/dev/lyzev/api/setting/settings/SettingClientSlider.kt
- src/main/kotlin/dev/lyzev/api/setting/settings/SettingClientText.kt
- src/main/kotlin/dev/lyzev/schizoid/feature/features/gui/guis/ImGuiScreenFeature.kt
- src/main/kotlin/dev/lyzev/schizoid/feature/features/module/modules/render/ModuleToggleableWaterMark.kt
- src/main/resources/assets/schizoid/shaders/core/GameOfLife/GameOfLife_CP.glsl
> should work as intended

- src/main/kotlin/dev/lyzev/api/imgui/render/renderable/ImGuiRenderableConfigManager.kt
> implemented the suggestion

- src/main/kotlin/dev/lyzev/schizoid/feature/features/module/Module.kt
- src/main/kotlin/dev/lyzev/schizoid/feature/features/module/modules/render/ModuleToggleableTargetHUD.kt
- src/main/resources/schizoid.accesswidener
> 104 suggestion target hud

- src/main/kotlin/dev/lyzev/schizoid/feature/features/module/Module.kt
> implemented suggestion

- src/main/kotlin/dev/lyzev/schizoid/feature/features/module/modules/render/ModuleToggleableModules.kt
> implemented Align Modules

- gradle/libs.versions.toml
> migrated Fabric

- src/main/java/dev/lyzev/schizoid/injection/mixins/minecraft/client/MixinMouse.java
- src/main/java/dev/lyzev/schizoid/injection/mixins/minecraft/client/input/MixinKeyboardInput.java
- src/main/java/dev/lyzev/schizoid/injection/mixins/minecraft/client/network/MixinClientPlayerEntity.java
- src/main/java/dev/lyzev/schizoid/injection/mixins/minecraft/client/render/entity/MixinLivingEntityRenderer.java
- src/main/java/dev/lyzev/schizoid/injection/mixins/minecraft/client/util/MixinWindow.java
> removed redirect

- src/main/kotlin/dev/lyzev/api/imgui/render/ImGuiRenderer.kt
- src/main/kotlin/dev/lyzev/api/opengl/shader/Shaders.kt
- src/main/kotlin/dev/lyzev/schizoid/feature/features/gui/guis/ImGuiScreenFeature.kt
close #125 
this should fix the crash
> fix crash on window resize

- src/main/kotlin/dev/lyzev/api/imgui/ImGuiLoader.kt
- src/main/kotlin/dev/lyzev/schizoid/feature/features/gui/guis/ImGuiScreenFeature.kt
> fix no mouse cursor change with other mods

- src/main/kotlin/dev/lyzev/api/imgui/render/renderable/ImGuiRenderableConfigManager.kt
- src/main/kotlin/dev/lyzev/schizoid/feature/Feature.kt
> added initial size and pos

- src/main/kotlin/dev/lyzev/api/opengl/shader/Shaders.kt
> possible fix

- src/main/kotlin/dev/lyzev/api/opengl/shader/Shaders.kt
- src/main/kotlin/dev/lyzev/schizoid/feature/features/gui/guis/ImGuiScreenFeature.kt
- src/main/resources/assets/schizoid/shaders/core/Random/Random_FP.glsl
- src/main/resources/assets/schizoid/shaders/core/Random/Random_VP.glsl
> did take way too long, sry

- src/main/kotlin/dev/lyzev/api/theme/OSTheme.kt
> fixed the crash bug

- src/main/kotlin/dev/lyzev/schizoid/feature/features/module/modules/movement/ModuleToggleableToggleSneak.kt
- src/main/kotlin/dev/lyzev/schizoid/feature/features/module/modules/player/ModuleToggleableFastPlace.kt
> added toggle sneak feature

- src/main/kotlin/dev/lyzev/api/imgui/render/renderable/ImGuiRenderableDeveloperTool.kt
- src/main/kotlin/dev/lyzev/api/opengl/WrappedFramebuffer.kt
- src/main/resources/assets/schizoid/shaders/core/Reflection/Reflection_FP.glsl
> added more dev tools

- src/main/kotlin/dev/lyzev/api/opengl/shader/Shaders.kt
- src/main/kotlin/dev/lyzev/api/opengl/shader/blur/BlurHelper.kt
- src/main/kotlin/dev/lyzev/schizoid/feature/features/module/modules/render/ModuleToggleableBlur.kt
- src/main/resources/assets/schizoid/shaders/core/Tint/Tint_FP.glsl
> fixed bug (second try)

- src/main/kotlin/dev/lyzev/schizoid/feature/features/module/modules/movement/ModuleToggleableToggleSneak.kt
- src/main/kotlin/dev/lyzev/schizoid/feature/features/module/modules/movement/ModuleToggleableToggleWalk.kt
> added toggle walk feature

- src/main/kotlin/dev/lyzev/api/imgui/render/renderable/ImGuiRenderableDeveloperTool.kt
- src/main/kotlin/dev/lyzev/api/opengl/WrappedFramebuffer.kt
- src/main/kotlin/dev/lyzev/api/opengl/shader/blur/blurs/BlurBox.kt
- src/main/kotlin/dev/lyzev/api/opengl/shader/blur/blurs/BlurDualKawase.kt
- src/main/kotlin/dev/lyzev/api/opengl/shader/blur/blurs/BlurGaussian.kt
- src/main/kotlin/dev/lyzev/api/opengl/shader/blur/blurs/BlurKawase.kt
- src/main/kotlin/dev/lyzev/api/opengl/shader/blur/blurs/BlurMovingAveragesBox.kt
> improved developer tool

- .github/workflows/release-nightly-build.yml
- .github/workflows/release.yml
- build.gradle.kts
- src/main/java/dev/lyzev/schizoid/injection/mixin/minecraft/client/render/MixinWorldRenderer.java
- src/main/kotlin/dev/lyzev/api/opengl/Render.kt
- src/main/kotlin/dev/lyzev/api/opengl/shader/Shader.kt
- src/main/kotlin/dev/lyzev/api/opengl/shader/Shaders.kt
- src/main/kotlin/dev/lyzev/api/opengl/shader/blur/BlurHelper.kt
- src/main/kotlin/dev/lyzev/schizoid/feature/features/module/modules/render/ModuleToggleableBlur.kt
- src/main/kotlin/dev/lyzev/schizoid/feature/features/module/modules/render/ModuleToggleableColorGrading.kt
- src/main/kotlin/dev/lyzev/schizoid/feature/features/module/modules/render/ModuleToggleableTorus.kt
- src/main/kotlin/dev/lyzev/schizoid/feature/features/module/modules/util/ModuleRunnableDepthTextureScreenshot.kt
- src/main/resources/assets/schizoid/shaders/core/Acrylic/Acrylic_FP.glsl
- src/main/resources/assets/schizoid/shaders/core/Tint/Tint_FP.glsl
- src/main/resources/assets/schizoid/shaders/include/RGBPukeCircle.glsl
- src/main/resources/assets/schizoid/shaders/include/RGBPukeNoise.glsl
> added rgb puke mode system

- build.gradle.kts
- gradle/libs.versions.toml
- gradle/wrapper/gradle-wrapper.properties
- src/main/java/dev/lyzev/schizoid/injection/mixin/minecraft/client/render/MixinCamera.java
- src/main/java/dev/lyzev/schizoid/injection/mixin/minecraft/client/render/MixinWorldRenderer.java
- src/main/java/dev/lyzev/schizoid/injection/mixin/minecraft/client/render/entity/MixinLivingEntityRenderer.java
- src/main/kotlin/dev/lyzev/api/events/Events.kt
- src/main/kotlin/dev/lyzev/api/opengl/Render.kt
- src/main/kotlin/dev/lyzev/api/opengl/shader/Shader.kt
- src/main/kotlin/dev/lyzev/api/opengl/shader/Shaders.kt
- src/main/kotlin/dev/lyzev/api/opengl/shader/blur/BlurHelper.kt
- src/main/kotlin/dev/lyzev/schizoid/feature/features/gui/guis/ImGuiScreenFeature.kt
- src/main/kotlin/dev/lyzev/schizoid/feature/features/module/modules/render/ModuleToggleableBlur.kt
- src/main/kotlin/dev/lyzev/schizoid/feature/features/module/modules/render/ModuleToggleableRearView.kt
- src/main/kotlin/dev/lyzev/schizoid/feature/features/module/modules/render/ModuleToggleableTorus.kt
- src/main/kotlin/dev/lyzev/schizoid/feature/features/module/modules/render/ModuleToggleableTrueSight.kt
- src/main/kotlin/dev/lyzev/schizoid/feature/features/module/modules/render/ModuleToggleableViewClip.kt
- src/main/resources/assets/schizoid/shaders/core/Depth/Depth_FP.glsl
- src/main/resources/schizoid.accesswidener
> bumped to 1.21

- build.gradle.kts
> change build configuration to include transient dependencies

- src/main/kotlin/dev/lyzev/api/account/accounts/AccountMicrosoft.kt
> fixed msa web login bug
